version: '3.9'
services:
  api:
    restart: always
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
      
  certbot:
    image: certbot/certbot:latest
    #docker-compose run --rm certbot certonly --webroot --webroot-path /var/www/certbot/ --dry-run -d domain_name -
    #docker-compose run --rm certbot certonly --webroot --webroot-path /var/www/certbot/ -d domain_name
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot

